version: "3.9"

services:
  app:
    container_name: catalog_films
    build: .
    ports:
      - "8090:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/var/www/html
  
  db:
    container_name: db
    image: postgres:12
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
    